### ISSUE TITLE
build.bundle.rxjs is failing

### ISSUE THREAD

**Issue by joseph77lee** [mgechev/angular-seed#2105]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Currently I'm getting the below error at build.bundle.rxjs with latest angular-seed

'build.bundle.rxjs' errored after 562 ms
Error on fetch for rxjs/operators at file:///clientdata/work/cm/src/angular/node_modules/rxjs/operators.js
  Loading rxjs/Rx
  Error: ENOENT: no such file or directory, open '/clientdata/work/cm/src/angular/node_modules/rxjs/operators.js'

**Expected behavior**
build.bundle.rxjs should work without errors.

**Minimal reproduction of the problem with instructions**
I tried..
npm cache clean
rm -rf node_modules
npm install

then I got above errors.

I think rxjs.5.5x. causing this issue. I downgraded to rxjs.5.4.x then working fine.

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.2:GA:server
Kernel: Linux 3.10.0-327.28.3.el7.x86_64
Architecture: x86-64

* **Angular Seed Version:** `aaaaf75`
ab4a98775935dcf8554a6b74d2620c2f84b90b29

* **Node:** `node --version` =
v7.9.0

**Comment by ogousa** [comment]
I have the same issue. 
Workaround: change "rxjs": "^5.4.3" to "rxjs": "5.4.3" in package.json

**Comment by teterovic** [comment]
Have the sam eissue

**Comment by mgechev** [comment]
Fix is pushed to master.

**Comment by zbarbuto** [comment]
Commit fixes the post-install hook but prod builds still failing for me.

**Comment by chrisbmoore** [comment]
This might be related to this problem: https://github.com/ReactiveX/rxjs/issues/2971. 

Hoping for a fix in RxJS 5.5.1. For now use @ogousa's advice and roll back to RxJS 5.4.3.

**Comment by zbarbuto** [comment]
Yeah that’s what I ended up doing. Thanks.

**Comment by ogousa** [comment]
btw, I get the @mgechev 's fix and it works in dev and prod mode for me.
